{
 "title": "Benchmark",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Artemis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "artemis_uptime_millis / 1000 / 60"
    }
   ]
  },
  {
   "title": "Journal Buffer Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "artemis_journal_buffer_size" },
    {}
   ]
  },
  {
   "title": "Journal Buffer Timeout",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "artemis_journal_buffer_timeout" },
    {}
   ]
  },
  {
   "title": "Journal Max I/O",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "artemis_journal_max_io" },
    {}
   ]
  },
  {
   "title": "Started",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "artemis_started" }
   ]
  },
  {
   "title": "Address Paging",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "artemis_paging" }
   ]
  },
  {
   "title": "Message Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    { "expr": "artemis_message_count", "legendFormat": "{{ address }}" }
   ]
  },
  {
   "title": "JMS Bridge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bridge Producer Byte Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(kafka_producer_producer_topic_metrics{name=\"byte-rate\"}) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "JMS Bridge Queue Add/Ack/Size",
     "type": "timeseries",
     "description": "The rate of messages being added and acked to/from a queue. Includes the total size of the queue which indicates queue depth.",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(artemis_messages_added{queue=~\".+\"}[$__rate_interval])",
       "legendFormat": "Adds {{queue}}"
      },
      {
       "expr": "rate(artemis_messages_acknowledged{queue=~\".+\"}[$__rate_interval])",
       "legendFormat": "Acks {{queue}}"
      },
      {
       "expr": "artemis_message_count{queue=~\".+\"}",
       "legendFormat": "Depth {{queue}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Benchmark Clients",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Producer Message Send Errors",
     "type": "stat",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "benchmark_producer_message_send_errors"
      }
     ]
    },
    {
     "title": "Benchmark Consumer Message Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 7, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "Messages" } },
     "targets": [
      {
       "expr": "rate(benchmark_consumer_messages_recv[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Benchmark Producer Message Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "Messages" } },
     "targets": [
      {
       "expr": "rate(benchmark_producer_messages_sent[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Benchmark E2E Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "benchmark_consumer_e2e_latency" }
     ]
    }
   ]
  }
 ]
}