global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'nodes-metrics'
    gce_sd_configs:
      - project: {{ controller_project }}
        zone: {{ controller_zone }}
        port: {{ controller_node_exporter_port }}
    relabel_configs:
      - source_labels: [__meta_gce_label_prometheus]
        regex: true.*
        action: keep
      - source_labels: [__meta_gce_label_node_exporter]
        regex: true.*
        action: keep
      - source_labels: [__meta_gce_instance_id]
        target_label: instance
      - source_labels: [__meta_gce_instance_name]
        target_label: name
      - source_labels: [__meta_gce_label_node]
        target_label: service

  - job_name: 'jmx-metrics'
    gce_sd_configs:
      - project: {{ controller_project }}
        zone: {{ controller_zone }}
        port: {{ prometheus_jmx_port }}
    relabel_configs:
      - source_labels: [__meta_gce_label_prometheus]
        regex: true.*
        action: keep
      - source_labels: [__meta_gce_label_jmx_exporter]
        regex: true.*
        action: keep
      - source_labels: [__meta_gce_instance_id]
        target_label: instance
      - source_labels: [__meta_gce_instance_name]
        target_label: name
      - source_labels: [__meta_gce_label_node]
        target_label: service

