# Docker compose for bringing up a local jms-bridge broker and dependencies.
#
# By default, the bridge has two brokers setup in HA.
#
# 2. Update .env file to use your local images by setting JMSBRIDGE_IMAGE_BASE=placeholder/ and JMSBRIDGE_VERSION=local.build.

---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:${CP_VERSION}
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-enterprise-kafka:${CP_VERSION}
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100

  schema-registry:
    image: confluentinc/cp-schema-registry:${CP_VERSION}
    depends_on:
      - zookeeper
      - kafka
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:32181

  live-jms-bridge:
    image: local.build/confluentinc/jms-bridge-docker:latest
    hostname: live-jms-bridge
    container_name: live-jms-bridge
    depends_on:
      - kafka
      - schema-registry
    ports:
      - "61616:61616"
      - "8888:8888"
      - "9999:9999"
    environment:
      #So you can hook up jconsole if so desired
      JMS_BRIDGE_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.rmi.port=9999 -Djava.rmi.server.hostname=192.168.1.144
      PROMETHEUS_ENABLED: "y"
      PROMETHEUS_PORT: 8888
      BROKER_XML: "broker.xml"
      LOG_IO_CONFLUENT_AMQ_EXCHANGE: INFO
      JMSBRIDGE_ID: local-docker
      JMSBRIDGE_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JMSBRIDGE_JOURNALS_TOPIC_REPLICATION: 1
      JMSBRIDGE_ROUTING_TOPICS_0_MATCH: "^jms-load-test.*"
      JMSBRIDGE_ROUTING_TOPICS_0_MESSAGE_TYPE: BYTES


# backup-jms-bridge:
#   image: ${JMSBRIDGE_IMAGE_BASE}confluentinc/jms-bridge-docker:${JMSBRIDGE_VERSION}
#   hostname: backup-jms-bridge
#   container_name: backup-jms-bridge
#   depends_on:
#     - live-jms-bridge
#   ports:
#     - "61617:61616"
#   environment:
#     BROKER_XML: "broker-backup-ha.xml"
#     JMSBRIDGE_ID: local-docker
#     JMSBRIDGE_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#     JMSBRIDGE_JOURNALS_TOPIC_REPLICATION: 1
#     JMSBRIDGE_ROUTING_TOPICS_0_MATCH: ".*"
#     JMSBRIDGE_ROUTING_TOPICS_0_MESSAGE_TYPE: BYTES
