#
# Copyright (C) 2021-2022 Confluent, Inc.
#

name: csid-jms-bridge
lang: java
lang_version: 17
github:
    enable: true
    repo_name: confluentinc/csid-jms-bridge
semaphore:
    enable: true
make:
  enable: true
  update_makefile: false
  enable_updates: true
git:
  enable: true
