{
 "title": "JMS Bridge Performance",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "bridgeInstance", "label": "Bridge Instance", "query": { "query": "jvm_memory_bytes_used" } }
  ]
 },
 "panels": [
  {
   "title": "Message Size",
   "type": "stat",
   "description": "The size of the message being published during this test in bytes.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "perf_test_message_size" }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(perf_test_messages_consumed_total[$__rate_interval]))",
     "legendFormat": "Max RPS"
    },
    {
     "expr": "avg(rate(perf_test_messages_consumed_total[$__rate_interval]))",
     "legendFormat": "Mean RPS"
    }
   ]
  },
  {
   "title": "Messages Consumed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "ceil(sum(perf_test_messages_consumed_total))"
    }
   ]
  },
  {
   "title": "Messages Published",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "ceil(sum(perf_test_messages_produced_total))",
     "legendFormat": "Total Sent"
    }
   ]
  },
  {
   "title": "Message Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(perf_test_producer_to_consumer_latency_ms_bucket[$__interval])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(perf_test_producer_to_consumer_latency_ms_bucket[$__interval])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(perf_test_producer_to_consumer_latency_ms_bucket[$__interval])) by (le))",
     "legendFormat": "75th"
    }
   ]
  },
  {
   "title": "Bridge Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(count(jvm_info{name=\"bridge-perf-bridge\"}))"
    }
   ]
  },
  {
   "title": "Test Nodes",
   "type": "stat",
   "description": "Each node has 1 JMS producer and 1 Kafka consumer",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(count(jvm_info{service=\"perf\"}))"
    }
   ]
  },
  {
   "title": "Message Latency",
   "type": "timeseries",
   "description": "The average time it takes for the test consumer to receive a message from the test publisher.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(perf_test_producer_to_consumer_latency_ms_bucket[$__interval])) by (name, le)) ",
     "legendFormat": "95th - {{name}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(perf_test_producer_to_consumer_latency_ms_bucket[$__interval])) by (name, le))",
     "legendFormat": "90th - {{name}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(perf_test_producer_to_consumer_latency_ms_bucket[$__interval])) by (name, le))",
     "legendFormat": "75th - {{name}}"
    }
   ]
  },
  {
   "title": "Test Publisher Throughput",
   "type": "timeseries",
   "description": "The rate at which the test producer(s) are publishing data into the JMS Bridge.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(rate(perf_test_messages_produced_total[$__rate_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(perf_test_messages_produced_total[$__rate_interval])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Test Consumer Throughput",
   "type": "timeseries",
   "description": "The rate at which the test Kafka consumer is reading messages from Kafka.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(perf_test_messages_consumed_total[$__rate_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(perf_test_messages_consumed_total[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bridge ($bridgeInstance) Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "repeat": "bridgeInstance",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", name=\"$bridgeInstance\"}",
     "legendFormat": "Heap Used"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\", name=\"$bridgeInstance\"}",
     "legendFormat": "Max Heap"
    }
   ]
  },
  {
   "title": "Bridge ($bridgeInstance) Consumption Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "repeat": "bridgeInstance",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_rate{name=~\"$bridgeInstance\", topic=~\".+\"}[$__interval])) by (topic, instance)",
     "legendFormat": "Topic {{topic}}"
    }
   ]
  },
  {
   "title": "Bridge ($bridgeInstance) Producer Byte Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "repeat": "bridgeInstance",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(kafka_producer_producer_topic_metrics_byte_rate{name=~\"$bridgeInstance\"}) by (topic)",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "JMS Bridge ($bridgeInstance) Address Size",
   "type": "timeseries",
   "description": "The rate of messages being added and acked to/from a queue. Includes the total size of the queue which indicates queue depth.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 31 },
   "repeat": "bridgeInstance",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(artemis_address_size{name=~\"$bridgeInstance\"}[$__interval]) > 0",
     "legendFormat": "{{address}} Size"
    }
   ]
  },
  {
   "title": "JMS Bridge ($bridgeInstance) Address Routed",
   "type": "timeseries",
   "description": "The rate of messages being added and acked to/from a queue. Includes the total size of the queue which indicates queue depth.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(artemis_routed_message_count{name=~\"$bridgeInstance\"}[$__interval])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "JMS Bridge ($bridgeInstance) Address Not Routed",
   "type": "timeseries",
   "description": "The rate of messages being added and acked to/from a queue. Includes the total size of the queue which indicates queue depth.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(artemis_un_routed_message_count{name=~\"$bridgeInstance\"}[$__interval])",
     "legendFormat": "Un-Routed {{address}}"
    }
   ]
  },
  {
   "title": "Active Bridge Instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(jvm_info{service=\"bridge\"})",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Active Test Instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(jvm_info{service=\"perf\"})",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Bridge ($bridgeInstance) CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "repeat": "bridgeInstance",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - rate(node_cpu_seconds_total{mode=\"idle\", name=\"$bridgeInstance\"}[$__interval])",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "Bridge ($bridgeInstance) network usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "repeat": "bridgeInstance",
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{name=\"$bridgeInstance\"}[$__interval])",
     "legendFormat": "Transmit"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{name=\"$bridgeInstance\"}[$__interval])",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Test Instance(s) CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", service=\"perf\"}[$__interval])) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Test Instance(s) network usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{service=\"perf\"}[$__rate_interval]))",
     "legendFormat": "Total Transmit"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{service=\"perf\"}[$__rate_interval]))",
     "legendFormat": "Total Receive"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{service=\"perf\"}[$__rate_interval])",
     "legendFormat": "Receive {{name}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{service=\"perf\"}[$__rate_interval])",
     "legendFormat": "Transmit {{name}}"
    }
   ]
  }
 ]
}