---
services:
  live:
    image: apache/activemq-artemis:latest
    environment:
      ARTEMIS_USER: artemis
      ARTEMIS_PASSWORD: artemis
      ANONYMOUS_LOGIN: true
    ports:
      - "61616:61616"
      - "8161:8161"
    volumes:
      - ./shared-store:/var/lib/artemis-instance/data
      - ./artemis-config/live-broker.xml:/var/lib/artemis-instance/etc-override/broker.xml
  backup:
    image: apache/activemq-artemis:latest
    environment:
      ARTEMIS_USER: artemis
      ARTEMIS_PASSWORD: artemis
      ANONYMOUS_LOGIN: true
    ports:
      - "61617:61617"
      - "8162:8161"
    volumes:
      - ./shared-store:/var/lib/artemis-instance/data
      - ./artemis-config/backup-broker.xml:/var/lib/artemis-instance/etc-override/broker.xml

  producer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAVA_FILE: Producer.java
    container_name: producer
    command: [ "-t", "test", "-d", "(tcp://live:61616,tcp://backup:61617)?ha=true&connection.sendTimeout=5000&retryInterval=1000&retryIntervalMultiplier=1.0&reconnectAttempts=-1&failoverOnServerShutdown=true;", "hello" ]
    depends_on:
      - live
      - backup
      - consumer
    restart: on-failure

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAVA_FILE: Consumer.java
    container_name: consumer
    command: [ "-t", "test", "-s", "(tcp://live:61616,tcp://backup:61617)?ha=true&retryInterval=1000&retryIntervalMultiplier=1.0&reconnectAttempts=-1;" ]
    depends_on:
      - live
      - backup
    restart: on-failure