apiVersion: v1alpha
kind: Project
metadata:
  name: cc-mk-include
  description: ""
spec:
  visibility: private
  repository:
    url: git@github.com:confluentinc/cc-mk-include.git
    run_on:
    - tags
    - branches
    - pull_requests
    - forked_pull_requests
    pipeline_file: .semaphore/semaphore.yml
    integration_type: github_app
    status:
      pipeline_files:
      - path: .semaphore/semaphore.yml
        level: pipeline
    whitelist:
      branches:
      - master
      - /^v\d+\.\d+\.x$/
  custom_permissions: true
  debug_permissions:
  - empty
  - default_branch
  - non_default_branch
  - pull_request
  - forked_pull_request
  - tag
  attach_permissions:
  - default_branch
  - non_default_branch
  - pull_request
  - forked_pull_request
  - tag
