{
 "title": "Jmeter",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "_agg_interval",
    "label": "Aggregate Interval",
    "query": "30s,1m,5m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Message Size",
   "type": "stat",
   "description": "The size of the message being published during this test in bytes.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jms_msg_size_summary" }
   ]
  },
  {
   "title": "Messages Published",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "ceil(sum(kafka_producer_producer_topic_metrics{name=\"record-send-total\", topic!~\"_?jms[.].+\"}))",
     "legendFormat": "Total Sent"
    }
   ]
  },
  {
   "title": "Messages Consumed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(jms_kafka_to_consumer_time_summary_count))"
    }
   ]
  },
  {
   "title": "JMeter Message Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(jms_producer_to_consumer_time_summary_bucket[$__rate_interval])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(jms_producer_to_consumer_time_summary_bucket[$__rate_interval])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(jms_producer_to_consumer_time_summary_bucket[$__rate_interval])) by (le))",
     "legendFormat": "75th"
    }
   ]
  },
  {
   "title": "Bridge Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", job=\"bridge-perf-bridge\"}",
     "legendFormat": "Heap Bridge"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\", job=\"bridge-perf-bridge\"}",
     "legendFormat": "Non-Heap Bridge"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\", job=\"bridge-perf-bridge\"}",
     "legendFormat": "Max Heap Bridge"
    }
   ]
  },
  {
   "title": "Bridge Producer Byte Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_producer_producer_topic_metrics{name=\"byte-rate\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Test Publisher Throughput",
   "type": "graph",
   "description": "The rate at which the test producer(s) are publishing data into the JMS Bridge.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "wps", "label": "Message Write Rate" }
   ],
   "targets": [
    {
     "expr": "rate(jms_sample_count{label=\"JMS Publisher\"}[$__rate_interval])",
     "legendFormat": "JMS Publish"
    }
   ]
  },
  {
   "title": "Test Consumer Throughput",
   "type": "graph",
   "description": "The rate at which the test Kafka consumer is reading messages from Kafka.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "rps", "label": "Message Read Rate" }
   ],
   "targets": [
    {
     "expr": "rate(jms_kafka_to_consumer_time_summary_count[$__rate_interval])",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "JMeter Message Latency",
   "type": "graph",
   "description": "The average time it takes for the test consumer to receive a message from the test publisher.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(jms_producer_to_consumer_time_summary_bucket[$_agg_interval])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(jms_producer_to_consumer_time_summary_bucket[$_agg_interval])) by (le)) ",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(jms_producer_to_consumer_time_summary_bucket[$_agg_interval])) by (le))",
     "legendFormat": "75th"
    }
   ]
  },
  {
   "title": "Latency Steps at 95th",
   "type": "graph",
   "description": "Latency for each step that a message passes through from producer to consumer",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ms", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(jms_producer_to_bridge_time_summary_bucket[$__interval])) by (le))",
     "legendFormat": "Producer2Kafka"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(jms_bridge_to_kafka_time_summary_bucket[$__interval])) by (le))",
     "legendFormat": "Bridge2Kafka"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(jms_kafka_to_consumer_time_summary_bucket[$__interval])) by (le))",
     "legendFormat": "Kafka2Consumer"
    }
   ]
  },
  {
   "title": "JMS Bridge Queue Add/Ack/Size",
   "type": "graph",
   "description": "The rate of messages being added and acked to/from a queue. Includes the total size of the queue which indicates queue depth.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Message Rate" }
   ],
   "targets": [
    {
     "expr": "rate(artemis_messages_added{queue=~\".+\"}[$__rate_interval])",
     "legendFormat": "Adds {{queue}}"
    },
    {
     "expr": "rate(artemis_messages_acknowledged{queue=~\".+\"}[$__rate_interval])",
     "legendFormat": "Acks {{queue}}"
    },
    {
     "expr": "artemis_message_count{queue=~\".+\"}",
     "legendFormat": "Depth {{queue}}"
    }
   ]
  }
 ]
}