# -*- coding: utf-8 -*-
from recommonmark.parser import CommonMarkParser
from recommonmark.transform import AutoStructify

project = u'JMS-Bridge'
copyright = u'2020, Confluent, Inc.'
version = '1.0-m1'
release = '1.0.0-m1'

# General options
needs_sphinx = '1.0'
master_doc = 'index'
pygments_style = 'sphinx'

extensions = ['sphinx.ext.autodoc']

templates_path = ['_templates']
exclude_trees = ['.build']
source_suffix = ['.rst', '.md']
source_encoding = 'utf-8-sig'
source_parsers = {
  '.md': CommonMarkParser
}
# Prefix document path to section labels, otherwise autogenerated labels would look like 'heading'
# rather than 'path/to/file:heading'
autosectionlabel_prefix_document = True

# PDF options
latex_engine = 'pdflatex'

# HTML options
html_theme = 'sphinx_rtd_theme'
html_last_updated_fmt = '%b %d, %Y'
html_copy_source = False

#> Note that the static resources are copied from
#> https://github.com/confluentinc/docs/tree/5.5.1-post/_static
html_static_path = ['_static']
htmlhelp_basename = 'Confluentdoc'

# def setup(app):
#   app.add_config_value('recommonmark_config', dict(
#     enable_auto_toc_tree=True,
#     auto_toc_tree_section='Contents'
#   ), True)
#   app.add_transform(AutoStructify)
